
services:
  postgres:
    image: postgres:16
    container_name: livraria_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - livraria_data:/var/lib/postgresql/data
    networks:
      - livraria_net

volumes:
  livraria_data:

networks:
  livraria_net:
